package controller;

import java.sql.*;

public final class DatabaseConnection {
    private static final String URL = "jdbc:h2:~/test";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private static DatabaseConnection singleton = new DatabaseConnection();

    private Connection connection;

    private DatabaseConnection() {
        try {
            Class.forName("org.h2.Driver");
            connect();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    public static DatabaseConnection getInstance() {
        return singleton;
    }

    private void connect() throws SQLException {
        if (connection == null || connection.isClosed()) {
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
        }
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        connect();
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }
    
    public PreparedStatement prepareStatement(String sql) throws SQLException {
       connect();
       return connection.prepareStatement(sql);
    }
    
    public Statement statement() throws SQLException {
       connect();
       return connection.createStatement();
    }

    public void close() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            connection = null;
        }
    }
}

