DROP SCHEMA IF EXISTS MYTOP10 CASCADE;

--DROP TABLE IF EXISTS MUSICA_TOP10;
--DROP TABLE IF EXISTS top10;
--DROP TABLE IF EXISTS musica;

CREATE TABLE IF NOT EXISTS top10 (
    ID SERIAL PRIMARY KEY,
    Descricao VARCHAR(255) NOT NULL,
    Titulo VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS musica (
    ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS  musica_top10 (
    ID SERIAL PRIMARY KEY,
    ID_musica VARCHAR(255),
    ID_top10 INT NOT NULL,
    ordem_musica INT,
    FOREIGN KEY (ID_top10) REFERENCES top10(ID) ON DELETE CASCADE
);
