DROP SCHEMA IF EXISTS MYTOP10 CASCADE;

CREATE SCHEMA MYTOP10;

SET SCHEMA 'MYTOP10';

CREATE TABLE top10 (
    ID SERIAL PRIMARY KEY,
    Descricao VARCHAR(255) NOT NULL,
    Titulo VARCHAR(255) NOT NULL
);

CREATE TABLE musica (
    ID SERIAL PRIMARY KEY,
    Descricao VARCHAR(255) NOT NULL
);

CREATE TABLE musica_top10 (
    ID SERIAL PRIMARY KEY,
    ID_musica INT NOT NULL,
    ID_top10 INT NOT NULL,
    ordem_musica INT,
    FOREIGN KEY (ID_top10) REFERENCES top10(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_musica) REFERENCES musica(ID) ON DELETE CASCADE
);
